version: "2"
run:
  go: "1.25"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - paralleltest
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    rules:
      - linters:
          - goconst
        path: .*_test\.go
      - linters:
          - errcheck
        source: defer
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
